### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by voron121** [lukaslangrock/ShutdownTimerClassic#20] opened 2022-07-25 20:07 UTC
### Hi! Getting error mesage whet start app. It's make me sad  :( 

Error: 

```
---- Process Info ----
PID: 6052
ProcessName: ShutdownTimerClassic
Arguments: 
PriorityClass: Normal
Threads: 6
Responding: True
HasExited: False
StartTime: 25.07.2022 23:00:18
PeakWorkingSet64: 16,9MB (17731584byte)
WorkingSet64: 16,9MB (17727488byte)
PeakWorkingSet64: 16,9MB (17731584byte)
PrivateMemorySize64: 9MB (9457664byte)
VirtualMemorySize64: 159,7MB (167481344byte)
PeakVirtualMemorySize64: 163,7MB (171606016byte)
PagedSystemMemorySize64: 228,9KB (234424byte)
NonpagedSystemMemorySize64: 17,2KB (17568byte)
PagedMemorySize64: 9MB (9457664byte)
PeakPagedMemorySize64: 9MB (9457664byte)
UserProcessorTime: 00:00:00.0937500
TotalProcessorTime: 00:00:00.1875000
PrivilegedProcessorTime: 00:00:00.0937500


---- Application Info ----
Product Name: ShutdownTimerClassic
Product Version: 1.2.3.0
Current Culture: ru-UA
Executable Path: C:\Program Files\WindowsApps\19341LukasLangrock.ShutdownTimerClassic_1.2.3.0_x64__jnfph5tq58r4j\ShutdownTimer\ShutdownTimerClassic.exe
MD5 Checksum: f755519e89e2e543ed11f113634d6e20


---- Environment Info ----
64-bit OS: True
64-bit Process: False
OS Version: Microsoft Windows NT 10.0.19044.0
Runtime Version: 4.0.30319.42000
System Uptime: 48740937
Machine Name: DESKTOP-B173R9C
Processor Count: 4
Shutdown Started: False


---- Exception ----
Type: UnhandledException
Message: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. Access is denied.
Stack Trace:
    at ShutdownTimer.Helpers.SettingsProvider.Load()
   at ShutdownTimer.Program.Main(String[] args)


---- Internal Event Log ----
[Program] Running Menu
[Program] Attaching ExceptionHandler.cs
```

**Comment by lukaslangrock** [comment] 2022-08-05 13:51
It seems to me that there was in issue with the installation. Please try uninstalling and then installing the app again.

**Comment by lukaslangrock** [comment] 2023-05-18 08:03
sorry, got it mixed up with another iissue

**Comment by lukaslangrock** [comment] 2024-04-19 15:45
I feel like this issue was caused by the way Windows Installed the App. I also didn't hear anything else about it, so I'll be closing this.
If anyone else has the same problem, please leave a comment. To fix your issue, re-installing the software should help.

**Closed by lukaslangrock** 2024-04-19 15:45 UTC
Labels: bug
